name: build-and-upload-installers
on:
  release:
    types: [published]
  push:
    branches:
      main
jobs:
  build-and-upload-installer:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            filename: macOS/Tailor-*.dmg
          - os: windows-latest
            filename: dist/*.msi
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: import certificates on macOS
        if: matrix.os == 'macos-latest'
        uses: ./.github/actions/import_apple_certs

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python -m pip install briefcase
      - run: briefcase create
      - run: python pruner.py
      - run: briefcase build

      - name: package briefcase app for Windows
        if: matrix.os == 'windows-latest'
        run: briefcase package
      - name: package briefcase app for macOS
        if: matrix.os == 'macos-latest'
        run: |
          briefcase package -i 'Developer ID Application: David Fokkema (HWB9PKA687)'

      - name: upload assets to release page
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ matrix.filename }}
          tag: ${{ github.ref }}
